name: FitDad
favicon: null
layout_spectrum: 0.4564967015758157
typography_spectrum: 0.5121455613989383
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.8427790403366089
  lightness: 0.3459640918299556
  saturation: 0.9361838221084327
  rhythmicContrast: 0.28509150445461273
purpose: []
